version: '3'
services:
  node1:
    build: .
    ports:
    - 7000
    links:
    - node2
    environment:
      PEER_PORT: 7532
      BOOTSTRAP_PEER: node2:7532
  node2:
    build: .
    ports:
    - 7000
    environment:
      PEER_PORT: 7532
      BOOTSTRAP_PEER: node1:7532
