version: '3'
services:
  node1:
    build: .
    ports:
    - 7000
    links:
    - node2
    environment:
      PEER_PORT: 7532
      BOOTSTRAP_IP: node2
      BOOTSTRAP_PORT: 7532
  node2:
    build: .
    ports:
    - 7000
    environment:
      PEER_PORT: 7532
      BOOTSTRAP_IP: node1
      BOOTSTRAP_PORT: 7532


